CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_team PRIMARY KEY (id),
  CONSTRAINT uk_team_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tournaments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_tournament PRIMARY KEY (id),
  CONSTRAINT uk_tournament_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  home_team_id BIGINT NOT NULL,
  away_team_id BIGINT NOT NULL,
  home_goals BIGINT NOT NULL,
  away_goals BIGINT NOT NULL,
  match_date TIMESTAMPTZ NOT NULL,
  tournament_id BIGINT NOT NULL,
  CONSTRAINT pk_match PRIMARY KEY (id),
  CONSTRAINT fk_home_team_id FOREIGN KEY (home_team_id) REFERENCES teams (id),
  CONSTRAINT fk_away_team_id FOREIGN KEY (away_team_id) REFERENCES teams (id),
  CONSTRAINT fk_tournament_id FOREIGN KEY (tournament_id) REFERENCES tournaments (id),
  CONSTRAINT unique_match UNIQUE (home_team_id, away_team_id, match_date)
);